(defun foo ()
  (let ((a 5))
    (defun bar (x)
      (setf a 9)
      (format t "~A~%" (+ a x)))
    (setf a 8)
    (bar 10)
    (format t "~A~%" a)
    (let ((a 25))
      (format t "~A~%" (bar 10)))))
